# Generated by Django 2.1.1 on 2018-12-02 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=django.utils.timezone.now)),
                ('Respuesta1', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, es un método por el cual un individuo, mediante un sistema informático, intenta tomar el control, desestabilizar o dañar otro sistema informático (ordenador, red privada, etcétera).', max_length=128)),
                ('Respuesta2', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, se deberia de contar con uno para la proteccion contra malware.', max_length=128)),
                ('Respuesta3', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, para controlar el acceso a ellos.', max_length=128)),
                ('Respuesta4', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='No, porque provienen de fuentes desconocidas y muchas veces contienen malware.', max_length=128)),
                ('Respuesta5', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, por si nuestro dispositivo llega a fallar tener nuestra informacion controlada.', max_length=128)),
                ('Respuesta6', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, porque logra proteger nuestro intereses en la red y cuidar nuestra informacion que dejamos.', max_length=128)),
                ('Respuesta7', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, para evitar la infeccion de virus.', max_length=128)),
                ('Respuesta8', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, es más seguro y normalmente contienen un hash para comprobar los archivos descargados.', max_length=128)),
                ('Respuesta9', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, es importante saber esto para poder mejorar la proteccion que le damos a nuestro equipo.', max_length=128)),
                ('Respuesta10', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, esto debido al hecho que contienen una mayor cantidad de clickbaits y malware.', max_length=128)),
                ('Respuesta11', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='No, las redes gratuitas normalmente están plagadas de malware y es facil que te puedan infectar, aparte los datos trasmitidos no son encriptados.', max_length=128)),
                ('Respuesta12', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, es importante conocerlas para no caer presas de terceros y no dejar tanta informacion en la red.', max_length=128)),
                ('Respuesta13', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, se calcula que al mes salen mas de 1000 viruses y por eso es importante siempre mantener actualizada la base de datos del antivirus.', max_length=128)),
                ('Respuesta14', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, normalmente las actualizaciones contienen mejores medidad de seguridad y por eso es bueno mantener acutalizados nuestros dispositivos.', max_length=128)),
                ('Respuesta15', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, es necesario saber esto para poder protegernos eficazmente contra ataques MITM, archivos auto-ejecutables, entre otros.', max_length=128)),
                ('Respuesta16', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, a traves de la ingenieria social nos pueden violentar nuestra seguridad, para poder protegernos es necario no dejar tanta informacion de nosotros en la red y no compartir informacion de nosotros con personas ajenas.', max_length=128)),
                ('Respuesta17', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, usualmente los pop-ups llegan a recabar informacion de nuestro navegador y para poder protegernos existen multiples instancias que pueden bloquearlos.', max_length=128)),
                ('Respuesta18', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, es necesario hacer esto para poder evitar que utilizen nuestros datos en nuestra contra y proteger la privacidad tuya y de otras personas.', max_length=128)),
                ('Respuesta19', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='Si, esto para que podamos recuperar nuestra informacion y en lagunos casos poder bloquear nuestro dispositivo de forma remota.', max_length=128)),
                ('Respuesta20', models.CharField(choices=[('2', 'Si'), ('0', 'No'), ('1', 'A veces')], help_text='No, esto puede representar una vulnerabilidad de seguridad y somo propensos a la ingenieria social y por lo tanto nuestra informacion sea facilmente violentada.', max_length=128)),
                ('Calificacion', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=254)),
                ('Ap_Paterno', models.CharField(max_length=254)),
                ('Ap_Materno', models.CharField(max_length=254)),
                ('Edad', models.CharField(max_length=3)),
                ('Correo', models.EmailField(max_length=254)),
                ('Genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lenguajes.DatosPersonales'),
        ),
    ]
