# Generated by Django 2.1.1 on 2018-12-02 18:42

import Lenguajes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lenguajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='Nombre',
            field=models.ForeignKey(default=Lenguajes.models.DatosPersonales, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lenguajes.DatosPersonales'),
        ),
    ]
