# Generated by Django 2.1.1 on 2018-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenguajes', '0002_auto_20181202_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='Num_Aveces',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Num_No',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='Num_Si',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
